### PR TITLE
Added osx travis build

### PR DESCRIPTION
**Pull request by pthom**
cf https://github.com/Dobiasd/FunctionalPlus/issues/147

Hi,

This PR adds two new builders to the travis matrix (xcode 9 and xcode 10)

I had to fight hard against travis inconsistencies, since python support is different on osx.

Details :
* locale tests adapted to osx (different locale names) 
* I had to reduce the timed_test.cpp expectations under osx, since these builders are very slow with travis
* I modified the badges on the readme file, but this commit can be reversed if desired

Thanks

### CODE REVIEW

**Comment by pthom** [comment]
Modif to the readme badges :

**Comment by Dobiasd** [comment]
Nice! But I have to admit, I might not be the best person to judge CI improvements like this. So if @offa does not have any objections, I'll merge. ;)

**Comment by offa** [comment]
Looks good :+1: 

Just an aesthetic note: I don't think the build bagdes need an descriptive text, they are well known on GH :smile: ) (and the readme breaks a bit unfortunate on my phone :confused:  ). However, that doesn't really matter …

We probably should add OS X Clang to the list of [supported compiler](https://github.com/Dobiasd/FunctionalPlus#requirements-and-installation).

**Comment by offa** [comment]
@pthom do you think we can close #147 once this PR has been merged?

**Pull request merged**
