### PR TITLE
Conan minimal support

### PR DESCRIPTION
**Pull request by danimtb**
Here you have a minimal support of Conan C/C++ pacakge manager in your library.
Files added are:

- *conanfile.py*: Conan "recipe" for this library. As you can see it quite trivial, only meta information and a package() method copying the header files with its license.
- *test_package*: It is a minimum setup test to check the conan package for FunctionalPLus has been created correctly. This is also a kind of way to show users of your library how to consume your library via Conan.

As you can see, the Conan recipe has the meta-information about the version "fixed" in it. Everytime you create a new release, the vesion inside *conanfile.py* needs to be bumped. You will also have to upload this manually to the **conan-center** repository like this:

```
$ conan create conanfile.py Dobiasd/stable
$ conan upload funtionalplus/<new_version_here>@Dobiasd/stable -r conan-center
```

If you want me to tweak Travis CI to perform this automatically when you tag a new version, just let me know and I will include the needed files.

Many thanks! 😄

### CODE REVIEW

**Comment by Dobiasd** [comment]
Hi Daniel,

thanks a lot! This looks good and not too complicated.

Sure, if it is not too much work for you (and does not increase the overall complexity of the CI integration of fplus too much), it would be great if you could add the support for the automatic upload of versions with a new tag. :)

If you prefer to not include it in this PR, just let me know, and I will merge this one first.

Tobias

**Comment by danimtb** [comment]
Yes, I will add the CI in this same PR! Stay tuned 😉

**Comment by Dobiasd** [comment]
I see you're industriously working on this. :)

The [last Travis build](https://travis-ci.org/Dobiasd/FunctionalPlus/builds/341427604) only failed because the clang 5 package could not be found. I restarted the according build job and this time it worked.

**Comment by danimtb** [comment]
@Dobiasd yes, sorry for the noise. I saw the clang-5.0 failing but dont know why it didn find the apt package...

**Comment by Dobiasd** [comment]
> I saw the clang-5.0 failing but dont know why it didn find the apt package...

Sometimes it just does that ...

**Comment by danimtb** [comment]
Done! have a look and tell me what you think :)

**Comment by Dobiasd** [comment]
To me (as a Conan rookie) it looks good, so I'll simply merge. : )

**Comment by danimtb** [comment]
Don't worry! Feel free to ask any issue related to Conan and I would support you  :)

Additionally, you will have to perform [few steps](http://docs.conan.io/en/latest/uploading_packages/bintray/uploading_bintray.html) for the package to be uploaded.

Basically, create a Bintray account with your name (you can login with GitHub oauth) and create a Conan repository called **public-conan** (This will be your particular repository). Next, setup Travis with an environment variable called ``CONAN_PASSWORD`` with the Bintray API key of your profile as value (make sure it is hidden). This way Travis will release a new package when you tag a new version of FunctionalPlus :)

Why do you have to create your own Bintray repository? Because **conan-center** is hosted in Bintray and the process of submiting a library is via inclusion-request. This means that packages from other repos are linked to central conan-center. For library authors (like you) who would like to include their library it is [as easy as clicking a button](http://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html).

I hope this makes sense and do not hesitate to ask me if you have any doubt during the process 😃

**Comment by Dobiasd** [comment]
Thanks for the additional explanation. It was easier for me to follow your customized description here compared to the [Uploading to Bintray steps](http://docs.conan.io/en/latest/uploading_packages/bintray/uploading_bintray.html). :-)

I created a [Bintray repo `public-conan`](https://bintray.com/dobiasd/public-conan) and added the Bintray API key to travis (screenshot):
CONAN_PASSWORD

Now I guess I just have to do the last step (clicking the button), right? However I feel dumb for not finding out what button is meant. Is it the green "Include My Package" button?
the_green_button
If so, what package name do I have to search for in the dialog that is opening up?
search_package_name

**Comment by Dobiasd** [comment]
Ah OK, I guess I found out. I had to first use the "Add New Package" button in my [public-conan repo](https://bintray.com/dobiasd/public-conan/). I just did that and now I have [bintray.com/dobiasd/public-conan/FunctionalPlus](https://bintray.com/dobiasd/public-conan/FunctionalPlus).

Now I can use the "Include My Package" button in `conan-center` to start a `Request to include the package 'FunctionalPlus' in 'Conan Center'`. However I get the following error: `Unable to send message: Empty packages are not allowed in Conan Center`. What do I have to do? :)

**Comment by danimtb** [comment]
Hi @Dobiasd, sorry for the delay,

Great to see you have created a public-conan repo successfully! The CONAN_PASSWORD in Travis seems right too! Thanks for sharing

To solve the rest of the issues, let me explain:

First of all, now I see your public-conan repository, you will have to change your username [here](https://github.com/Dobiasd/FunctionalPlus/blob/0dc56fcabcfa538cb9970cba44c27a9246233c53/conan_build.py#L10) and [here](https://github.com/Dobiasd/FunctionalPlus/blob/0dc56fcabcfa538cb9970cba44c27a9246233c53/conan_build.py#L12) to **dobiasd** instead of **Dobiasd**.

You have created packages manually and both of them are empty so there is no "real" package there. To upload a real package right now we have two options:

1.- Release a new version of FunctionalPlus and let Travis CI generate the conan package and upload it.
2.- Generate the Conan package and upload it manually (steps to follow in your machine):
```
$ conan remote add <REMOTE> https://api.bintray.com/conan/dobiasd/public-conan 
$ conan user -p <APIKEY> -r <REMOTE> <USERNAME>
$ cd FunctionalPlus
$ conan create conanfile.py functionalplus/0.2@dobiasd/stable # This will create the package
$ conan upload functionalplus/0.2@dobiasd/stable --all -r <REMOTE>
```

Yes, https://bintray.com/conan-community/conan/functionalplus:conan is a apackage uploaded by me just before I reached you here to support conan. It is not in conan-center and will be deleted as soon as your own FunctionalPlus package is uploaded, so no worries :)

Finally, we are aware the UI in Bintray is a bit weird and sometimes not so user friendly. The button to perform an inclusion-request is [this one](http://docs.conan.io/en/latest/_images/add_to_conan-center.png).

Hope this helps and thank you for your patience.

**Comment by Dobiasd** [comment]
Thanks a lot for the support,

I [adjusted the case of my username](https://github.com/Dobiasd/FunctionalPlus/commit/f3163ba7a504780bbdc50f7e8943e47a9ca4102e) and created [a new release](https://github.com/Dobiasd/FunctionalPlus/releases/tag/v0.2-p1).

Travis CI did its job and now there is [bintray.com/dobiasd/public-conan/functionalplus:dobiasd](https://bintray.com/dobiasd/public-conan/functionalplus%3Adobiasd).

Then I used the "Add to Conan Center" button.

Now I think I can delete the manually created packages ([1](https://bintray.com/dobiasd/public-conan/FunctionalPlus), [2](https://bintray.com/dobiasd/public-conan/frugally-deep)), and add the currently missing information (website link, licence, logo etc.) in the automatically generated one, right?

**Comment by danimtb** [comment]
Great news! I am really pleased that it worked :D
I will review your inclusion request ASAP.

Yes, you can delete the manually created ones and it would be nice to have all the information filled in the new one to make it easier for users to find your library.

I would like to give you one idea here to improve your library with Conan in the future:
- **doctest optional dependency**: You can manage optional dependencies with Conan too. In case you want to run the tests you can add an option to your library and make Conan resolve the [doctest dependency](https://bintray.com/bincrafters/public-conan/doctest:bincrafters) for you. [Here is a simple example](https://docs.conan.io/en/latest/howtos/header_only.html) on how to run tests in header only libraries.

Thank you so much for your patience and understanding and I hope you like Conan 😄

**Comment by Dobiasd** [comment]
> Yes, you can delete the manually created ones and it would be nice to have all the information filled in the new one to make it easier for users to find your library.

Done.

I will see if I can make progress with frugally-deep and Conan during the next days and get back to you [there](https://github.com/Dobiasd/frugally-deep/issues/12).

Thanks again. :+1:

**Pull request merged**
