### PR TITLE
Feature/generic lambdas

### PR DESCRIPTION
**Pull request by theodelrieu**
Hi, I think the library is fully converted :)

There is some stuff to clean up yet, but feature-wise it's done (assuming I didn't miss anything).

I overhauled some methods in the meantime.

### CODE REVIEW

**Comment by theodelrieu** [comment]
Once this PR is rebased and merged I believe it would be great to merge it into master, before the commit pile becomes too high (it's quite high already).

I will open cleanup PRs after that.

**Comment by Dobiasd** [comment]
Outstanding work! The attention to details is also great, for example
* making `logical_not` variadic
* utilizing `using std::begin;` in `fold` etc. to facilitate ADL

**Comment by Dobiasd** [comment]
My availability during the next 4 days is quite low, so I suggest we merge into master during next week.

But at least I just ~~fixed~~ [worked around](https://github.com/Dobiasd/FunctionalPlus/commit/c2066f60844ff77464d6dbbb950eaa8be436b418) the travis problem we were also facing in this PR. ;)

**Comment by Dobiasd** [comment]
@theodelrieu OK, it is [merged](https://github.com/Dobiasd/FunctionalPlus/pull/104/) into master. I guess we can delete the branch "Feature/generic lambdas" now, right?

**Comment by theodelrieu** [comment]
Yep!

**Pull request merged**
