### PR TITLE
Zip repeat

### PR DESCRIPTION
**Pull request by unixnme**
I am adding zip_repeat, as you have suggested in #227 .

### CODE REVIEW

**Comment by Dobiasd** [comment]
Thanks a lot. In general, it looks good to me. The implementation is not full of `if`s and nicely symmetric. :+1:  The tests are also nicely concise. :slightly_smiling_face:

I'm just a bit worried about the need for the forward declaration. As far as I remember, this was not needed up to now. Do we have a problem with our include-dependency tree?

**Comment by unixnme** [comment]
> I'm just a bit worried about the need for the forward declaration. As far as I remember, this was not needed up to now. Do we have a problem with our include-dependency tree?

With `zip_repeated`, yes. We now have generate.hpp -> numeric.hpp -> pairs.hpp -> generate.hpp.
Options that I can think of are
1. forward declare
2. implement zip_repeat w/o using existing repeat
3. move `repeat` to a different header, maybe container_common?

Any idea / suggestion on this?

**Comment by Dobiasd** [comment]
Ah, yeah. I just checked out your branch

```bash
git clone https://github.com/Dobiasd/FunctionalPlus
cd FunctionalPlus
git fetch origin pull/228/head:zip_repeat
git checkout zip_repeat
```

and checked for circular includes like [so](https://github.com/Dobiasd/FunctionalPlus/issues/184#issuecomment-698169328), and it printed:

```
1 cycles found:
['fplus_numeric_hpp', 'fplus_pairs_hpp', 'fplus_generate_hpp']
```

We should avoid having circles. :)

---

Regarding your three options:

1. Meh.
2. Would not be beautiful, but ok.
3. Would be ok too. Even users who did not `#include <fplus/fplus.hpp>` but only `#include <fplus/generate.hpp>` and use `repeat` would still be ok, since `generate.hpp` includes `container_common.hpp`. Actually, I did this move multiple times in the past. Many things in `container_common.hpp` are just there because I tried to avoid cycles. :grin:

But in this case, I think there is a fourth, even simpler, solution. I think `generate.hpp` does even need to include `numeric.hpp`. So removing that include should fix the problem. :slightly_smiling_face:

**Comment by unixnme** [comment]
> But in this case, I think there is a fourth, even simpler, solution. I think `generate.hpp` does even need to include `numeric.hpp`. So removing that include should fix the problem. 🙂

fantastic! Fixed now 👍 
Not sure why my IDE was not able to flag it as unused #include

**Comment by Dobiasd** [comment]
:tada:

From my point of view, we are ready to merge. What do you think?

**Comment by unixnme** [comment]
> 🎉
> 
> From my point of view, we are ready to merge. What do you think?

looks good to me too!

**Comment by Dobiasd** [comment]
:+1:

I've updated the [API search](http://www.editgym.com/fplus-api-search/) accordingly:

x82Mf32

**Pull request merged**
