### PR TITLE
Add Homebrew install

### PR DESCRIPTION
**Pull request by SeekingMeaning**
https://formulae.brew.sh/formula/functionalplus

### CODE REVIEW

**Comment by Dobiasd** [comment]
Thanks. But I get `Error: No available formula with the name "functionalplus"` ([`Dockerfile`](https://gist.github.com/Dobiasd/b33244d2953df43053b750c8536035a6)).

Any idea on how to make it work? (I have no experience with `brew`.)

**Comment by SeekingMeaning** [comment]
Hmm try `brew update` and then do `brew install functionalplus`

**Comment by SeekingMeaning** [comment]
Oh wait you're using Ubuntu

**Comment by SeekingMeaning** [comment]
`functionalplus` was added recently so it should take a day or so for `linuxbrew-core` to update

**Comment by Dobiasd** [comment]
Ah, ok, thanks. I'll try again tomorrow and once it ([`Dockerfile`](https://gist.github.com/Dobiasd/4a59e73f54f1c540fa1d28f335631897)) works, I'll merge this PR. :+1:

**Comment by SeekingMeaning** [comment]
Opened an issue: Homebrew/linuxbrew-core#20798

**Comment by Dobiasd** [comment]
It's installing now. :+1:

But using my [`Dockerfile`](https://gist.github.com/Dobiasd/cdf857e31a9e3fb297aa477b68c7fb1a) compilation [fails with `main.cpp:1:10: fatal error: fplus/fplus.hpp: No such file or directory`](https://gist.github.com/Dobiasd/01bb00110d31ba40009151bf3387a751).

Could you give me a hint on what to do, and then also add it for to this PR, so our users don't run into the same issue?

**Comment by SeekingMeaning** [comment]
Try adding `-I$(brew --prefix functionalplus)/include` or `-I/home/linuxbrew/.linuxbrew/opt/functionalplus/include` to `RUN g++`

**Comment by Dobiasd** [comment]
Works nicely, thanks. :+1:
I've [added a remark about this](https://github.com/Dobiasd/FunctionalPlus/commit/a9d9d2125aedc288220cceb3d78729b75bd23eb9) to the docs.

**Pull request merged**
