### PR TITLE
Adding curried versions of min_on and max_on

### PR DESCRIPTION
**Pull request by pmalek**
I believe this is the missing piece that we have been talking about in #21 :)

### CODE REVIEW

**Comment by Dobiasd** [comment]
That is awesome! I was expecting come very complicated template magic, but your solution is beautifully simple.

Of course I still respect the engineering art that you put into the non-curried versions, but to reduce code complexity and to avoid having overloaded functions (for binding, using with `transform`, `zip` etc) I think we should remove them now. Do you agree?

**Comment by pmalek** [comment]
Well it all depends on your usage but sure. If you don't see their use then we can remove them.

**Comment by Dobiasd** [comment]
Oh, I just realized, we can not remove them completely of course, because the curried version uses the non curried version. But I [moved it into the `internal` namespace](https://github.com/Dobiasd/FunctionalPlus/commit/935d584f887da729df44763599c6edcedd482cac).

Could you explain the difference between the versions for POD types and the version for non-POD types to me? Is there more to it than passing PODs per value and non-PODs per ref to const?

**Comment by pmalek** [comment]
As of the current version there is no difference besides passing by lvalue/const ref.

I was wondering (and I still am) whether it would be better to use rvalue references in function signature there but I will have to get to higher level of expertise on them to reason about it:)

**Comment by Dobiasd** [comment]
OK, thanks. An `int` or something alike should be faster passed by value than by ref to const, but right now this differentiation is made nowhere else in the library. I would love to have consistency here. Adapting everything else to this differentiation would increase the overall complexity a lot and make everything less DRY. So I think we should drop the pass-by-value versions. Do you approve this plan?

**Pull request merged**
