### PR TITLE
Clang 14 build

### PR DESCRIPTION
**Pull request by offa**
Adds a build for the recently released Clang 14.

### CODE REVIEW

**Comment by offa** [comment]
Strange, MSVC 2016 was cancelled immediately.

**Comment by Dobiasd** [comment]
Weird. And [it](https://github.com/Dobiasd/FunctionalPlus/runs/5818865875) only [tells](https://i.imgur.com/RvkhIVK.png) "This check was cancelled" without telling the reason. :shrug:

**Comment by Dobiasd** [comment]
Yeah, sounds good. :+1:

**Comment by offa** [comment]
I'll submit a separate PR.

**Pull request merged**
