### PR TITLE
Fixed split_by compilation error for GCC 10

### PR DESCRIPTION
**Pull request by ruanformigoni**
Pull request related to issue #170 .

### CODE REVIEW

**Comment by Dobiasd** [comment]
Hi Ruan,

thanks a lot for submitting this fix.

However, the Microsoft compiler (MSVC) [seems to not like](https://ci.appveyor.com/project/Dobiasd/functionalplus/builds/31962418/job/nvrtv43em8et1eif) that version using `*itOut = std::insert_iterator<ContainerOut>{};`. And idea how we could make it work for that too without introducing some `#ifdef _MSC_VER` stuff?

**Comment by Dobiasd** [comment]
Ah, sorry, it's not just the MSVC build that fails, but GCC and Clang fail too:

https://travis-ci.org/github/Dobiasd/FunctionalPlus/builds/671193078

**Comment by Dobiasd** [comment]
How about `*itOut = typename ContainerOut::value_type();` instead?

**Comment by ruanformigoni** [comment]
Nice one, it worked! Thank you! :grin:

**Comment by Dobiasd** [comment]
Cool. Squashed and merged. Thanks again for bringing this up. :+1:

**Pull request merged**
