### PR TITLE
Doctest v2.3.4

### PR DESCRIPTION
**Pull request by offa**
Doctest v2.2.3 wasn't found by conan (it's not available any more!?)

### CODE REVIEW

**Comment by Dobiasd** [comment]
I was expecting old versions to usually still be available, but ok. :man_shrugging:

Thanks a lot for the fix. :heart:

**Comment by offa** [comment]
I wonder why travis doesn't show up!? :question:

**Comment by Dobiasd** [comment]
Looks OK now:

gND6qJZ

Nybx4vt

**Comment by offa** [comment]
But the status isn't shown on Github (only appveyor).

**Comment by Dobiasd** [comment]
I think recently, it only shows the green or the red status, but no longer the yellow one.

We could make `master` fail to check if it updates then. :wink:

**Comment by Dobiasd** [comment]
Or, maybe by some internal magic it remembers that this build already passed when it ran on the branch, so it does not change the status while (re-)building. Also only testable with pushing some dummy commit to `master` directly, I guess.

**Comment by offa** [comment]
Seems others experience the problem too: https://travis-ci.community/t/github-status-not-posted-on-commits-on-repositories-using-legacy-service-integration/7798

**Comment by Dobiasd** [comment]
Ah, so maybe we should [migrate](https://docs.travis-ci.com/user/migrate/legacy-services-to-github-apps-migration-guide/), I guess.

**Comment by offa** [comment]
No, legacy build still work and should post their result :-)
I hope travis devs fix this soon. But until then I guess we can't do much.

**Pull request merged**
